# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8992ef7ccd8c3b13b098c1f372475f7d0d7f119364fddccb7767bc545d3a8d1c3672895d2f7f82157f394678ef197573dd91d7755cf69d0e4c53dcec878a8f7b

test:
  secret_key_base: fc4d7bc1ccb48c8fd1517a9e9974f3cab5815d2e179c609bf92898dce8d93282855a303f8298b138bbbc056eb6ffd49c40d30b5928ca285883496656dfee35af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
